"""add_screenshot_path_to_payment_requests

Revision ID: 18533d9e08f5
Revises: b4bf5567358g
Create Date: 2025-12-16 00:28:04.328678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18533d9e08f5'
down_revision: Union[str, Sequence[str], None] = 'b4bf5567358g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('screenshot_path', sa.String(length=500), nullable=True))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('payment_requests', 'screenshot_path')
    # ### end Alembic commands ###
