"""Add payment_requests table

Revision ID: a3ae4456247f
Revises: 9ece5370f509
Create Date: 2025-12-14 20:28:22.504725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ae4456247f'
down_revision: Union[str, Sequence[str], None] = '9ece5370f509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upi_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_requests_created', 'payment_requests', ['created_at'], unique=False)
    op.create_index('idx_payment_requests_status', 'payment_requests', ['status'], unique=False)
    op.create_index('idx_payment_requests_user', 'payment_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_requests_user', table_name='payment_requests')
    op.drop_index('idx_payment_requests_status', table_name='payment_requests')
    op.drop_index('idx_payment_requests_created', table_name='payment_requests')
    op.drop_table('payment_requests')
    # ### end Alembic commands ###
